"""
Django settings for logtrack project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env if present (tiny inline loader; no python-dotenv dep)
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _k, _, _v = _line.partition('=')
        os.environ.setdefault(_k.strip(), _v.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b-^3sn1!6$m08@x(bb&m=kd%e-ee%07!ute61-qcc&lytt%ip+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mill',
    'bokio',
]

UNFOLD = {
    'SITE_TITLE': 'Logtrack',
    'SITE_HEADER': 'Logtrack',
    'SITE_SUBHEADER': 'Stockar & virke',
    'SIDEBAR': {
        'show_search': False,
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'Sågverk',
                'items': [
                    {
                        'title': 'Stockar',
                        'icon': 'forest',
                        'link': reverse_lazy('admin:mill_log_changelist'),
                    },
                    {
                        'title': 'Virke',
                        'icon': 'inventory_2',
                        'link': reverse_lazy('admin:mill_lumber_changelist'),
                    },
                    {
                        'title': 'Trädslag',
                        'icon': 'park',
                        'link': reverse_lazy('admin:mill_species_changelist'),
                    },
                    {
                        'title': 'Avkastning',
                        'icon': 'monitoring',
                        'link': reverse_lazy('mill:yield_report'),
                    },
                    {
                        'title': 'Klingobyten',
                        'icon': 'content_cut',
                        'link': reverse_lazy('mill:blade_sessions'),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logtrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logtrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'sv'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# --- Lumber pricing (suggested-price formula; user can override per row) ---
# Base price is the customer-facing per-meter price for LUMBER_BASE_DIM,
# *including* 25% VAT. suggested_price_sek divides by (1 + LUMBER_VAT_RATE)
# so the stored price is ex VAT (what Bokio expects on line items).
LUMBER_BASE_PRICE_SEK_PER_M = Decimal('46.00')
LUMBER_BASE_DIM_W_MM = 95
LUMBER_BASE_DIM_T_MM = 45
LUMBER_VAT_RATE = Decimal('0.25')


# --- Bokio API ---
BOKIO_TOKEN = os.environ.get('BOKIO_TOKEN', '')
BOKIO_COMPANY_ID = os.environ.get('BOKIO_COMPANY_ID', '')
BOKIO_API_BASE = os.environ.get('BOKIO_API_BASE', 'https://api.bokio.se/v1')
