# Generated by Django 6.0.5 on 2026-05-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_cm', models.PositiveSmallIntegerField()),
                ('length_cm', models.PositiveSmallIntegerField()),
                ('source', models.CharField(blank=True, max_length=128)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('mill_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-mill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('latin_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_mm', models.PositiveSmallIntegerField()),
                ('width_mm', models.PositiveSmallIntegerField()),
                ('length_mm', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('green', 'Green (fresh)'), ('drying', 'Drying'), ('dry', 'Dry / ready'), ('sold', 'Sold / removed')], default='green', max_length=16)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lumber', to='mill.log')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='mill.species'),
        ),
    ]
