# Generated by Django 6.0.5 on 2026-05-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-mill_date', '-id'], 'verbose_name': 'stock', 'verbose_name_plural': 'stockar'},
        ),
        migrations.AlterModelOptions(
            name='lumber',
            options={'ordering': ['-id'], 'verbose_name': 'virke', 'verbose_name_plural': 'virke'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'trädslag', 'verbose_name_plural': 'trädslag'},
        ),
        migrations.AlterField(
            model_name='log',
            name='diameter_cm',
            field=models.PositiveSmallIntegerField(verbose_name='toppdiameter (cm)'),
        ),
        migrations.AlterField(
            model_name='log',
            name='length_cm',
            field=models.PositiveSmallIntegerField(verbose_name='längd (cm)'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mill_date',
            field=models.DateField(verbose_name='sågdatum'),
        ),
        migrations.AlterField(
            model_name='log',
            name='notes',
            field=models.TextField(blank=True, verbose_name='anteckningar'),
        ),
        migrations.AlterField(
            model_name='log',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='mottaget'),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(blank=True, max_length=128, verbose_name='ursprung'),
        ),
        migrations.AlterField(
            model_name='log',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='mill.species', verbose_name='trädslag'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='antal'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='length_mm',
            field=models.PositiveIntegerField(verbose_name='längd (mm)'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='location',
            field=models.CharField(blank=True, max_length=64, verbose_name='plats'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lumber', to='mill.log', verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='notes',
            field=models.TextField(blank=True, verbose_name='anteckningar'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='status',
            field=models.CharField(choices=[('green', 'färskt'), ('drying', 'torkar'), ('dry', 'torrt'), ('sold', 'sålt / borta')], default='green', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='thickness_mm',
            field=models.PositiveSmallIntegerField(verbose_name='tjocklek (mm)'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='width_mm',
            field=models.PositiveSmallIntegerField(verbose_name='bredd (mm)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='latinskt namn'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='namn'),
        ),
    ]
