# Generated by Django 6.0.5 on 2026-05-25 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0002_alter_log_options_alter_lumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='status ändrad'),
        ),
    ]
