# Generated by Django 6.0.5 on 2026-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0003_lumber_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='bokio_invoice_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Bokio-faktura-id'),
        ),
        migrations.AddField(
            model_name='lumber',
            name='bokio_line_item_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Bokio-radobjekt-id'),
        ),
        migrations.AddField(
            model_name='lumber',
            name='unit_price_sek',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pris per styck (ex moms)'),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='status',
            field=models.CharField(choices=[('green', 'färskt'), ('drying', 'torkar'), ('dry', 'torrt')], default='green', max_length=16, verbose_name='status'),
        ),
    ]
