# Generated by Django 6.0.5 on 2026-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0005_sold_to_dry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='diameter_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='toppdiameter (cm)'),
        ),
    ]
