# Generated by Django 6.0.5 on 2026-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0006_alter_log_diameter_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fresh_blade_mounted',
            field=models.BooleanField(default=False, help_text='Markera den första stocken som sågades med en nymonterad klinga.', verbose_name='ny klinga monterad'),
        ),
    ]
