# Generated by Django 6.0.5 on 2026-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0007_log_fresh_blade_mounted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='status',
            field=models.CharField(choices=[('green', 'färskt'), ('dry', 'torrt'), ('picked_up', 'hämtat'), ('delivered', 'levererad'), ('used_farm', 'använt gården'), ('used_private', 'använt privat')], default='green', max_length=16, verbose_name='status'),
        ),
    ]
